version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    #network_mode: service:db
    ports: 
      - "8000:5000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: retroolympics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432"

volumes:
  postgres-data: