name: Python CI

on:  
  pull_request:
    types: [opened, labeled]
    branches: main

defaults:
  run:
    working-directory: ./backend

jobs:
  check-code-quality:
    if: contains(github.event.pull_request.labels.*.name, 'backend')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
      - name: Run lint with ruff
        run: ruff backend
      - name: Check formatting with black
        run: black --check backend
      - name: Check imports with isort
        run: isort --check backend
